### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Eddman** [Eddman/DAVe#1]
- [ ] sorting
- [ ] colspan in position reports history (detail row)
- [ ] -0.00 in Margin Shortfall Surplus
- [ ] Tree map
- [ ] highlighting
- [ ] replacing rows closes the opened rows
- [ ] Find out how to remove decorators in generated AoT JS bundle
- [ ] Memory leak? App crash in few hours?

**Comment by Eddman** [comment]
Opened issues:
- [ ] open row button looses state on replace
- [ ] highlighting
- [ ] Line charts full size not correct when labels are as percentage
- [ ] Tree map
- [ ] Find out how to remove decorators in generated AoT JS bundle
- [ ] Update with keyof for TS 2.1+

**Comment by Eddman** [comment]
Nice to have:

- [ ] Find out how to remove decorators in generated AoT JS bundle
- [ ] Update with keyof for TS 2.1+
